name: Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: 4po10
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
